name: Playwright E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Run Browser E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps ${{ matrix.project }}

      - name: Pull Forum Docker Image
        run: docker pull freboot/forum-private:latest

      - name: Start Forum Docker Container
        run: |
          docker run -d --name forum -p 8070:8080 freboot/forum-private:latest
          sleep 5

      - name: Wait for server to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8070 > /dev/null 2>&1; then
              echo "Server is ready!"
              exit 0
            fi
            echo "Waiting for server... ($i/30)"
            sleep 2
          done
          echo "Server failed to start"
          exit 1

      - name: Run Playwright Tests
        run: npx playwright test --project=${{ matrix.project }}
        env:
          BASE_URL: http://localhost:8070
          CI: true

      - name: Stop Forum Docker Container
        if: always()
        run: |
          docker stop forum || true
          docker rm forum || true

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report/
          retention-days: 30

      - name: Upload Test Videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-videos-${{ matrix.project }}
          path: test-results/
          retention-days: 30

      - name: Upload Test Traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-traces-${{ matrix.project }}
          path: test-results/**/*.zip
          retention-days: 30